stages:
- publish

default:
  image: node
  tags: [ docker ]

variables:
  VSCE_BASE_CONTENT_URL: ${CI_PROJECT_URL}/-/blob/${CI_COMMIT_SHA}/
  VSCE_BASE_IMAGE_URL: ${CI_PROJECT_URL}/-/raw/${CI_COMMIT_SHA}/
  JOB_TOKEN_HEADER: 'Job-Token: ${CI_JOB_TOKEN}'
  PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/myawesomerelease/${PACKAGE_VERSION}"

package:
  stage: publish
  script:
  - yarn install --frozen-lockfile
  - yarn global add vsce
  - vsce package --baseContentUrl $VSCE_BASE_CONTENT_URL --baseImagesUrl $VSCE_BASE_IMAGE_URL

publish:open-vsx:
  stage: publish
  rules: [{ if: '$CI_COMMIT_TAG =~ /^v(\d+)\.(\d+)\.(\d+)/'}]
  environment:
    name: open-vsx
    url: https://open-vsx.org/extension/ethan-reesor/vscode-byebug
  release:
    tag_name: $CI_COMMIT_TAG
    description: Release $CI_COMMIT_TAG
  script:
  - VERSION=$(node -e "console.log('$CI_COMMIT_TAG'.slice(1))")
  - yarn install --frozen-lockfile
  - yarn global add vsce json ovsx
  - json -I -f package.json -e "this.version = '$VERSION'"
  - NAME=$(node -e "console.log(require('./package.json').name)")
  - PKG_URL="${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${NAME}/${VERSION}"
  - VSIX="${NAME}-${VERSION}.vsix"
  - vsce package --baseContentUrl $VSCE_BASE_CONTENT_URL --baseImagesUrl $VSCE_BASE_IMAGE_URL
  - curl -H "$JOB_TOKEN_HEADER" --upload-file ${VSIX} ${PKG_URL}/${VSIX}
  - ovsx publish --packagePath ${VSIX}