stages:
- package
- publish

default:
  image: node
  tags: [ docker ]

variables:
  VSCE_BASE_CONTENT_URL: ${CI_PROJECT_URL}/-/blob/${CI_COMMIT_SHA}/
  VSCE_BASE_IMAGE_URL: ${CI_PROJECT_URL}/-/raw/${CI_COMMIT_SHA}/
  JOB_TOKEN_HEADER: 'Job-Token: ${CI_JOB_TOKEN}'
  PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/myawesomerelease/${PACKAGE_VERSION}"

package:
  stage: package
  rules: [{ if: '$CI_COMMIT_TAG !~ /^v(\d+)\.(\d+)\.(\d+)/'}]
  artifacts:
    expire_in: 1 week
    paths:
    - '*.vsix'
  script:
  - yarn install --frozen-lockfile
  - yarn global add vsce
  - vsce package --baseContentUrl $VSCE_BASE_CONTENT_URL --baseImagesUrl $VSCE_BASE_IMAGE_URL

package:release:
  stage: package
  rules: [{ if: '$CI_COMMIT_TAG =~ /^v(\d+)\.(\d+)\.(\d+)/'}]
  artifacts:
    expire_in: 1 week
    paths:
    - '*.vsix'
  script:
  - yarn install --frozen-lockfile
  - yarn global add vsce json
  - json -I -f package.json -e "this.version = '$CI_COMMIT_TAG'.slice(1)"
  - vsce package --baseContentUrl $VSCE_BASE_CONTENT_URL --baseImagesUrl $VSCE_BASE_IMAGE_URL

publish:gitlab-release:
  stage: publish
  rules: [{ if: '$CI_COMMIT_TAG =~ /^v(\d+)\.(\d+)\.(\d+)/'}]
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  script: echo
  release:
    tag_name: $CI_COMMIT_TAG
    description: Release $CI_COMMIT_TAG

publish:gitlab-package:
  stage: publish
  rules: [{ if: '$CI_COMMIT_TAG =~ /^v(\d+)\.(\d+)\.(\d+)/'}]
  script:
  - NAME=$(node -e "console.log(require('./package.json').name)")
  - VERSION=$(node -e "console.log('$CI_COMMIT_TAG'.slice(1))")
  - PKG_URL="${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${NAME}/${VERSION}"
  - VSIX="${NAME}-${VERSION}.vsix"
  - curl -H "$JOB_TOKEN_HEADER" --upload-file ${VSIX} ${PKG_URL}/${VSIX}

publish:open-vsx:
  stage: publish
  rules: [{ if: '$CI_COMMIT_TAG =~ /^v(\d+)\.(\d+)\.(\d+)/'}]
  environment:
    name: open-vsx
    url: https://open-vsx.org/extension/ethan-reesor/vscode-byebug
  script:
  - yarn global add ovsx json
  - VSIX=$(node -e 'console.log(`${require("./package.json").name}-${"'$CI_COMMIT_TAG'".slice(1)}.vsix`)')
  - json -I -f package.json -e "this.version = '$CI_COMMIT_TAG'.slice(1)"
  - ovsx publish --packagePath ${VSIX}

publish:visual-studio:
  stage: publish
  rules: [{ if: '$CI_COMMIT_TAG =~ /^v(\d+)\.(\d+)\.(\d+)/'}]
  environment:
    name: visual-studio
    url: https://marketplace.visualstudio.com/items?itemName=ethan-reesor.vscode-byebug
  script:
  - yarn global add vsce json
  - VSIX=$(node -e 'console.log(`${require("./package.json").name}-${"'$CI_COMMIT_TAG'".slice(1)}.vsix`)')
  - json -I -f package.json -e "this.version = '$CI_COMMIT_TAG'.slice(1)"
  - vsce publish --packagePath ${VSIX}